(()=>{
const KEY='volleyverseClubs';
const defaults={name:'',tag:'VV',members:1,level:1,xp:0,wins:0,losses:0,contribution:0};
const load=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const need=l=>100+(l-1)*50;
const addXP=n=>{const s=load();s.xp+=Math.max(0,n);while(s.xp>=need(s.level)&&s.level<50){s.xp-=need(s.level);s.level++}save(s);render();return s};
const create=name=>{const s=load();if(s.name)return s;s.name=(name||'VOLLEY LEGENDS').trim().slice(0,18)||'VOLLEY LEGENDS';s.tag=s.name.replace(/[^A-Za-z]/g,'').slice(0,3).toUpperCase()||'VV';save(s);render();return s};
const record=won=>{const s=load();if(won){s.wins++;s.contribution+=25;addXP(50)}else{s.losses++;s.contribution+=10;save(s);render()}return load()};
const render=()=>{const s=load();const name=document.getElementById('clubName'),tag=document.getElementById('clubTag'),level=document.getElementById('clubLevel'),xp=document.getElementById('clubXP'),fill=document.getElementById('clubFill'),wins=document.getElementById('clubWins'),losses=document.getElementById('clubLosses'),con=document.getElementById('clubContribution');if(name)name.textContent=s.name||'NO CLUB';if(tag)tag.textContent=s.tag;if(level)level.textContent='LEVEL '+s.level;if(xp)xp.textContent=s.xp+' / '+need(s.level)+' XP';if(fill)fill.style.width=Math.min(100,s.xp/need(s.level)*100)+'%';if(wins)wins.textContent=s.wins;if(losses)losses.textContent=s.losses;if(con)con.textContent=s.contribution};
const open=()=>{let m=document.getElementById('clubModal');if(!m){m=document.createElement('div');m.id='clubModal';m.className='modal';m.innerHTML='<div class="modal-panel club-panel"><button class="modal-close" id="clubClose">×</button><span class="eyebrow">CLUBS & GUILDS</span><h2 id="clubName">NO CLUB</h2><div class="club-tag" id="clubTag">VV</div><div class="club-create"><input id="clubInput" maxlength="18" placeholder="Club name"><button class="primary" id="clubCreate">CREATE CLUB</button></div><div class="club-level"><b id="clubLevel">LEVEL 1</b><span id="clubXP">0 / 100 XP</span><div><i id="clubFill"></i></div></div><div class="club-stats"><div><b id="clubWins">0</b><span>WINS</span></div><div><b id="clubLosses">0</b><span>LOSSES</span></div><div><b id="clubContribution">0</b><span>CONTRIBUTION</span></div></div><button class="glass" id="clubDemo">SIMULATE CLUB WIN +50 XP</button><p class="club-note">Club prototype foundation: identity, progression, contribution and match history. Online member synchronization comes later.</p></div></div>';document.body.appendChild(m);document.getElementById('clubClose').onclick=()=>m.classList.add('hidden');document.getElementById('clubCreate').onclick=()=>create(document.getElementById('clubInput').value);document.getElementById('clubDemo').onclick=()=>record(true)}render();m.classList.remove('hidden')};
window.VVClubs={load,save,create,record,addXP,open};
})();