import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $ = id => document.getElementById(id);
const wrap = $('canvasWrap');
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x050914); scene.fog = new THREE.Fog(0x050914,22,48);
const camera = new THREE.PerspectiveCamera(56,innerWidth/innerHeight,.1,100); camera.position.set(0,8.2,14.5);
const renderer = new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; wrap.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xbfe8ff,0x0a1020,2.15)); const key=new THREE.DirectionalLight(0xffffff,3.3); key.position.set(5,13,8); key.castShadow=true; key.shadow.mapSize.set(1024,1024); scene.add(key); const rim=new THREE.PointLight(0x3d8cff,22,22); rim.position.set(-8,7,-5); scene.add(rim);
const court=new THREE.Group(); scene.add(court); const floor=new THREE.Mesh(new THREE.BoxGeometry(18,.22,10),new THREE.MeshStandardMaterial({color:0x165a83,roughness:.66,metalness:.04})); floor.position.y=-.14; floor.receiveShadow=true; court.add(floor);
function courtLine(x,z,w,d){const m=new THREE.Mesh(new THREE.BoxGeometry(w,.026,d),new THREE.MeshBasicMaterial({color:0xf2fbff}));m.position.set(x,.012,z);court.add(m)}
courtLine(0,-5,18,.08);courtLine(0,5,18,.08);courtLine(-9,0,.08,10);courtLine(9,0,.08,10);courtLine(0,-3,18,.055);courtLine(0,3,18,.055);courtLine(0,0,.055,10);
const net=new THREE.Group(); const poleMat=new THREE.MeshStandardMaterial({color:0xd9e7f4,metalness:.72,roughness:.25}); for(const x of[-4.65,4.65]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,2.7,12),poleMat);pole.position.set(x,1.35,0);pole.castShadow=true;net.add(pole)} const netMesh=new THREE.Mesh(new THREE.BoxGeometry(9.3,1.05,.045),new THREE.MeshBasicMaterial({color:0xe5edf5,transparent:true,opacity:.42,wireframe:true}));netMesh.position.y=1.75;net.add(netMesh);scene.add(net);
function createPlayer(color,name,x,z,home=true,position='OH',stats={}){const g=new THREE.Group();g.position.set(x,0,z);const jersey=new THREE.MeshStandardMaterial({color,roughness:.46});const skin=new THREE.MeshStandardMaterial({color:0xf0ae87,roughness:.7});const dark=new THREE.MeshStandardMaterial({color:0x111728,roughness:.65});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.31,.72,6,12),jersey);torso.position.y=1.04;torso.castShadow=true;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.27,16,12),skin);head.position.y=1.82;head.castShadow=true;g.add(head);const shorts=new THREE.Mesh(new THREE.BoxGeometry(.49,.3,.31),dark);shorts.position.y=.57;shorts.castShadow=true;g.add(shorts);const arms=[],legs=[];for(const sx of[-.4,.4]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.068,.5,5,8),skin);arm.position.set(sx,1.1,0);arm.rotation.z=sx<0?-.2:.2;arm.castShadow=true;g.add(arm);arms.push(arm)}for(const sx of[-.14,.14]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.075,.52,5,8),skin);leg.position.set(sx,.27,0);leg.castShadow=true;g.add(leg);const shoe=new THREE.Mesh(new THREE.BoxGeometry(.18,.1,.31),new THREE.MeshStandardMaterial({color:home?0xeaf8ff:0xffffff,roughness:.38}));shoe.position.set(sx,.055,home?-.04:.04);shoe.castShadow=true;g.add(shoe)}
const marker=new THREE.Mesh(new THREE.RingGeometry(.48,.57,32),new THREE.MeshBasicMaterial({color:0x5ee8ff,transparent:true,opacity:.9,side:THREE.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.position.y=.025;marker.visible=home;g.add(marker);
const arrow=new THREE.Mesh(new THREE.ConeGeometry(.11,.28,4),new THREE.MeshBasicMaterial({color:0x5ee8ff}));arrow.rotation.x=Math.PI;arrow.position.y=2.45;arrow.visible=home;g.add(arrow);
g.userData={name,home,position,stats,speed:3.9+(stats.speed||0)*.012,baseX:x,baseZ:z,arms,legs,action:0,cooldown:0,marker,arrow};scene.add(g);return g}
const defaultIds=['astra','kairo','nova','rex','mira','zen'];
const savedIds=JSON.parse(localStorage.getItem('volleyverseRoster')||'null')||defaultIds;
const roster=(window.VVCharacters?.roster||[]); const picked=savedIds.map(id=>roster.find(c=>c.id===id)).filter(Boolean); const squad=picked.length===6?picked:defaultIds.map(id=>roster.find(c=>c.id===id)).filter(Boolean);
const positions=[[-5.8,-3.45],[-2.2,-3.45],[2.2,-3.45],[-5.8,-1.15],[-2.2,-1.15],[2.2,-1.15]];
const homePlayers=squad.map((c,i)=>createPlayer(c.color,c.name,positions[i][0],positions[i][1],true,c.position,c.stats));
const awayData=[{name:'Vex',position:'OH',color:0xff4f79},{name:'Luna',position:'S',color:0xff4f79},{name:'Orion',position:'OPP',color:0xff4f79},{name:'Kai',position:'MB',color:0xff8847},{name:'Sora',position:'MB',color:0xff8847},{name:'Axel',position:'L',color:0xff8847}];
const awayPlayers=awayData.map((c,i)=>createPlayer(c.color,c.name,positions[i][0],-positions[i][1],false,c.position,{}));
const ball=new THREE.Mesh(new THREE.SphereGeometry(.19,20,14),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.28}));ball.castShadow=true;scene.add(ball);
const ballState={v:new THREE.Vector3(),active:false,lastTouch:'home',phase:'serve',touches:0,rallyTouches:0,cooldown:0}; let homeScore=0,awayScore=0,homeSets=0,awaySets=0,setNumber=1; let controlled=homePlayers[0]||null; let controlledIndex=0; let paused=false,rallyLocked=false; let servingTeam='home'; const keys={x:0,z:0};
function updateHUD(){$('homeScore').textContent=homeScore;$('awayScore').textContent=awayScore;$('setNumber').textContent=setNumber;$('setStatus').textContent=setNumber===5?'15':'25';const s=$('controlledPlayer');if(s&&controlled)s.textContent=controlled.userData.name.toUpperCase()+' • '+controlled.userData.position}
function setTip(t){$('tip').textContent=t}
function updateControlledVisual(){homePlayers.forEach((p,i)=>{p.userData.marker.visible=i===controlledIndex;p.userData.arrow.visible=i===controlledIndex})}
function resetPlayers(){[...homePlayers,...awayPlayers].forEach(p=>{p.position.x=p.userData.baseX;p.position.z=p.userData.baseZ;p.position.y=0;p.userData.action=0;p.userData.cooldown=0})}
function resetBall(){ballState.active=false;ballState.phase='serve';ballState.touches=0;ballState.rallyTouches=0;ballState.cooldown=0;ballState.lastTouch=servingTeam;ball.position.set(servingTeam==='home'?controlled.position.x:0,1.9,servingTeam==='home'?-4.25:4.25);ballState.v.set(0,0,0);rallyLocked=false;if(servingTeam==='home')setTip('TAP SERVE TO START • '+controlled.userData.name.toUpperCase());else{setTip('RIVALS SERVING • RECEIVE THE BALL');setTimeout(aiServe,500)}}
function rotateHome(){if(homePlayers.length<6)return;const old=homePlayers.map(p=>({x:p.userData.baseX,z:p.userData.baseZ}));const rotated=[old[5],old[0],old[1],old[2],old[3],old[4]];homePlayers.forEach((p,i)=>{p.userData.baseX=rotated[i].x;p.userData.baseZ=rotated[i].z;p.position.x=rotated[i].x;p.position.z=rotated[i].z});setTip('ROTATION • NEW COURT POSITIONS')}
function switchPlayer(){if(rallyLocked||!homePlayers.length)return;controlledIndex=(controlledIndex+1)%homePlayers.length;controlled=homePlayers[controlledIndex];updateControlledVisual();updateHUD();setTip('CONTROL • '+controlled.userData.name.toUpperCase()+' '+controlled.userData.position);if(!ballState.active)resetBall()}
function serve(){if(ballState.active||rallyLocked||servingTeam!=='home')return;ball.position.set(controlled.position.x,1.95,-4.15);const direction=THREE.MathUtils.clamp(controlled.position.x*.06,-.65,.65);ballState.v.set(direction,5.8,8.5);ballState.active=true;ballState.phase='serve';ballState.lastTouch='home';ballState.rallyTouches=1;setTip('SERVE IN PLAY • MOVE INTO POSITION');controlled.userData.action=.45}
function aiServe(){if(servingTeam!=='away'||ballState.active||rallyLocked)return;const server=awayPlayers[1]||awayPlayers[0];ball.position.set(server.position.x,1.95,4.15);ballState.v.set((Math.random()-.5)*.7,5.8,-8.5);ballState.active=true;ballState.phase='serve';ballState.lastTouch='away';ballState.rallyTouches=1;server.userData.action=.45;setTip('RIVALS SERVE • RECEIVE THE BALL')}
function playerNearBall(player,range=2.15){const dx=ball.position.x-player.position.x,dz=ball.position.z-player.position.z;return Math.hypot(dx,dz)<range&&Math.abs(ball.position.y-1)<2.2}
function action(type){if(rallyLocked)return;if(type==='serve'){serve();return}if(!ballState.active)return;if(ballState.cooldown>0)return;const dx=ball.position.x-controlled.position.x;const near=Math.hypot(dx,ball.position.z-controlled.position.z)<(type==='dive'?2.65:2.25);if(!near||ball.position.y<.25||ball.position.y>4.3)return;if(type==='pass'){ballState.v.set(dx*.18,6.3,4.8);ballState.phase='receive';setTip('PASS • BUILD THE ATTACK')}else if(type==='set'){ballState.v.set(dx*.12,7.35,4.2);ballState.phase='set';setTip('SET • PREPARE THE SPIKE')}else if(type==='spike'){ballState.v.set(dx*.15,4.9,10.9);ballState.phase='attack';setTip('SPIKE • ATTACK THE OPPONENT')}else if(type==='block'){if(ball.position.z>-.8&&ball.position.y>1.25){ballState.v.set(dx*.2,5.8,-Math.abs(ballState.v.z)*.9||-6.5);ballState.phase='block';setTip('BLOCK • CLOSE THE ANGLE')}else return}else if(type==='dive'){controlled.position.z=THREE.MathUtils.clamp(controlled.position.z+.7,-4.65,-.3);ballState.v.set(dx*.28,5.5,4.2);ballState.phase='dig';setTip('DIG • KEEP THE RALLY ALIVE')}controlled.userData.action=type==='dive'?.8:.55;ballState.lastTouch='home';ballState.touches=Math.min(ballState.touches+1,3);ballState.rallyTouches++;ballState.cooldown=.25}
['pass','set','spike','block','dive','serve'].forEach(type=>$(type+'Btn').addEventListener('pointerdown',e=>{e.preventDefault();action(type)}));$('switchBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();switchPlayer()});$('pauseBtn').addEventListener('pointerdown',()=>{paused=!paused;$('pauseBtn').textContent=paused?'▶':'Ⅱ';setTip(paused?'MATCH PAUSED':'RALLY LIVE • MOVE AND PLAY')});$('playBtn').addEventListener('pointerdown',()=>{$('overlay').classList.add('hidden');if($('playBtn').textContent==='PLAY AGAIN'){homeScore=awayScore=homeSets=awaySets=0;setNumber=1;servingTeam='home';controlledIndex=0;controlled=homePlayers[0];updateControlledVisual();updateHUD();resetPlayers();resetBall();$('overlayTitle').textContent='READY?';$('overlayText').textContent='Move your player, receive, set, spike and defend.';$('playBtn').textContent='PLAY MATCH'}});
const joy=$('joystick'),stick=$('stick');function joyMove(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy;const max=r.width*.32,len=Math.hypot(x,y);if(len>max){x*=max/len;y*=max/len}stick.style.transform=`translate(${x}px,${y}px)`;keys.x=x/max;keys.z=y/max}function joyEnd(){stick.style.transform='translate(0,0)';keys.x=keys.z=0}joy.addEventListener('pointerdown',e=>{joy.setPointerCapture(e.pointerId);joyMove(e)});joy.addEventListener('pointermove',e=>{if(e.pressure||e.buttons)joyMove(e)});joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);
let aiSequence=0;function aiUpdate(dt){const target=ballState.active?ball.position.x:0;awayPlayers.forEach((p,i)=>{const roleTarget=i===1?THREE.MathUtils.clamp(target,-6.8,6.8):p.userData.baseX+(target-p.userData.baseX)*.16;p.position.x+=THREE.MathUtils.clamp(roleTarget-p.position.x,-1,1)*dt*(1.35+i*.05);const desiredZ=i<3?3.25:1;p.position.z+=((ballState.active&&ball.position.z>.15?ball.position.z:desiredZ)-p.position.z)*dt*.55;p.position.x=THREE.MathUtils.clamp(p.position.x,-8.3,8.3);p.position.z=THREE.MathUtils.clamp(p.position.z,.35,4.65);p.userData.cooldown=Math.max(0,p.userData.cooldown-dt)});if(!ballState.active||ball.position.z<.05||ballState.cooldown>0)return;const receiver=awayPlayers.reduce((best,p)=>Math.abs(p.position.x-ball.position.x)<Math.abs(best.position.x-ball.position.x)?p:best,awayPlayers[0]);if(playerNearBall(receiver,2)&&receiver.userData.cooldown<=0&&ball.position.y<2.9){const attack=ball.position.y>1.8&&ball.position.z<2&&aiSequence%3===0;if(attack){ballState.v.set((Math.random()-.5)*1.1,5,-10.2);ballState.phase='attack';setTip('OPPONENT ATTACK')}else{ballState.v.set((Math.random()-.5)*1.4,6.3,-4.5);ballState.phase='receive'}ballState.lastTouch='away';ballState.rallyTouches++;receiver.userData.action=.5;receiver.userData.cooldown=.7;ballState.cooldown=.35;aiSequence++}}
function point(winner){if(rallyLocked)return;rallyLocked=true;if(winner==='home')homeScore++;else awayScore++;if(winner==='home'&&ballState.lastTouch==='away'){servingTeam='home';rotateHome()}else if(winner==='away'){servingTeam='away'}updateHUD();const target=setNumber===5?15:25,lead=Math.abs(homeScore-awayScore);if((homeScore>=target||awayScore>=target)&&lead>=2){if(homeScore>awayScore)homeSets++;else awaySets++;if(homeSets>=3||awaySets>=3){$('overlayTitle').textContent=homeSets>awaySets?'VICTORY':'DEFEAT';$('overlayText').textContent=`Match complete • ${homeSets}–${awaySets} sets`;$('playBtn').textContent='PLAY AGAIN';$('overlay').classList.remove('hidden');homeScore=awayScore=homeSets=awaySets=0;setNumber=1;servingTeam='home'}else{const setWinner=homeScore>awayScore?'home':'away';setNumber++;homeScore=awayScore=0;servingTeam=setWinner;setTip(`SET ${setNumber} • FIRST TO ${setNumber===5?15:25}`)}}else setTip(`${winner==='home'?'POINT VOLLEYVERSE':'OPPONENT POINT'} • ${servingTeam==='home'?'TAP SERVE':'GET READY TO RECEIVE'}`);resetPlayers();setTimeout(resetBall,650)}
function checkBall(dt){ballState.v.y-=9.8*dt;ball.position.addScaledVector(ballState.v,dt);ballState.cooldown=Math.max(0,ballState.cooldown-dt);if(ball.position.y<.18){point(ball.position.z<0?'away':'home');return}if(Math.abs(ball.position.x)>9.05||Math.abs(ball.position.z)>5.05){point(ball.position.z<0?'away':'home');return}if(Math.abs(ball.position.z)<.12&&ball.position.y<1.78){if(Math.abs(ballState.v.z)>.4)ballState.v.z*=-.72;ball.position.z=ball.position.z<0?-.14:.14}ballState.v.multiplyScalar(Math.pow(.998,dt*60));if(ballState.v.length()>15)ballState.v.setLength(15)}
function animatePlayer(p,dt,time){const u=p.userData;u.action=Math.max(0,u.action-dt*1.8);const moving=p===controlled&&Math.abs(keys.x)+Math.abs(keys.z)>.08;const stride=moving?Math.sin(time*12)*.35:Math.sin(time*3+p.position.x)*.025;u.legs[0].rotation.x=stride;u.legs[1].rotation.x=-stride;const lift=u.action>.05?Math.sin((.8-u.action)*8)*.22:0;p.position.y=Math.max(0,lift);u.arms[0].rotation.z=-.18-u.action*.8;u.arms[1].rotation.z=.18+u.action*.8;if(u.marker.visible){u.marker.rotation.z+=dt*1.8;u.arrow.position.y=2.45+Math.sin(time*4)*.06}}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.033),time=performance.now()*.001;if(!paused){controlled.position.x+=keys.x*controlled.userData.speed*dt;controlled.position.z+=-keys.z*controlled.userData.speed*dt;controlled.position.x=THREE.MathUtils.clamp(controlled.position.x,-8.25,8.25);controlled.position.z=THREE.MathUtils.clamp(controlled.position.z,-4.65,-.3);homePlayers.forEach(p=>{if(p===controlled)return;const shade=ballState.active&&ball.position.z<.2?(ball.position.x-p.position.x)*.07:0;p.position.x+=(p.userData.baseX+shade-p.position.x)*dt*.8;p.position.z+=(p.userData.baseZ-p.position.z)*dt*.8});aiUpdate(dt);if(ballState.active)checkBall(dt);[...homePlayers,...awayPlayers].forEach(p=>animatePlayer(p,dt,time))}const target=new THREE.Vector3(controlled.position.x*.18,1.15,controlled.position.z*.08);camera.position.lerp(new THREE.Vector3(target.x,7.75,13.9),.045);camera.lookAt(target);renderer.render(scene,camera)}
updateHUD();updateControlledVisual();resetBall();animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5))});
