const $ = id => document.getElementById(id);
const mainMenu = $('mainMenu'), modeMenu = $('modeMenu'), infoModal = $('infoModal'), characterMenu = $('characterMenu');
const gameUI = [...document.querySelectorAll('.game-ui')];
let controlMode=localStorage.getItem('volleyverseControlMode')||'team';
let lockPlayerIndex=Number(localStorage.getItem('volleyverseLockPlayer')||0);
function syncControlModeUI(){document.querySelectorAll('[data-control-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.controlMode===controlMode));const picker=$('playerLockPicker');picker?.classList.toggle('hidden',controlMode!=='lock');const roster=window.VVCharacters?.roster||[];const ids=window.VVCharacters?.selectedRoster?.()||['astra','kairo','nova','rex','mira','zen'];const box=$('playerLockOptions');if(box)box.innerHTML=ids.map((id,i)=>{const c=roster.find(x=>x.id===id);return c?`<button class="lock-player ${i===lockPlayerIndex?'selected':''}" data-lock-index="${i}">${c.name}<small>${c.position} • ${c.ovr}</small></button>`:''}).join('');box?.querySelectorAll('[data-lock-index]').forEach(b=>b.addEventListener('click',()=>{lockPlayerIndex=Number(b.dataset.lockIndex);localStorage.setItem('volleyverseLockPlayer',lockPlayerIndex);syncControlModeUI()}))}
document.querySelectorAll('[data-control-mode]').forEach(b=>b.addEventListener('click',()=>{controlMode=b.dataset.controlMode;localStorage.setItem('volleyverseControlMode',controlMode);syncControlModeUI()}));
function showGame(){mainMenu.classList.add('hidden');modeMenu.classList.add('hidden');characterMenu.classList.add('hidden');infoModal.classList.add('hidden');$('careerModal')?.classList.add('hidden');gameUI.forEach(el=>el.classList.remove('hidden'));window.scrollTo(0,0);syncControlModeUI()}
function showInfo(title,text){$('modalTitle').textContent=title;$('modalText').textContent=text;infoModal.classList.remove('hidden')}
function openCareer(){infoModal.classList.add('hidden');$('careerModal')?.classList.remove('hidden');window.VVCareer?.open()}
document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.action;if(a==='play'){mainMenu.classList.add('hidden');characterMenu.classList.remove('hidden')}else if(a==='training'){mainMenu.classList.add('hidden');characterMenu.classList.remove('hidden')}else if(a==='characters'){window.VVCharacters?.openCharacterSelect('main')}else if(a==='career')openCareer();else if(a==='ranked')window.VVRanked?.open();else if(a==='customize')showInfo('CUSTOMIZE','Design your team identity with uniforms, numbers, shoes, accessories and court cosmetics.');else if(a==='clubs')window.VVClubs?.open();else if(a==='world')window.VVWorldChampionship?.open() }));
$('playerChip')?.addEventListener('click',openCareer);
$('backToMenu').addEventListener('click',()=>{modeMenu.classList.add('hidden');mainMenu.classList.remove('hidden')});
$('closeModal').addEventListener('click',()=>infoModal.classList.add('hidden'));$('modalPlay').addEventListener('click',()=>infoModal.classList.add('hidden'));$('settingsBtn').addEventListener('click',()=>showInfo('SETTINGS','Gameplay, audio, graphics quality and control customization will be added as the game systems expand.'));
document.querySelectorAll('[data-mode]').forEach(card=>card.addEventListener('click',()=>{if(card.classList.contains('locked'))return;const mode=card.dataset.mode;if(mode==='training')showInfo('TRAINING','Training mode is being prepared. For now, the playable 3D court prototype launches from Real Match.');else if(mode==='local')$('localModal')?.classList.remove('hidden');else showGame()}));
function syncMenuProfile(){const s=window.VVCareer?.load?.();if(!s)return;const rank=window.VVCareer.rank(s.level);$('menuRank').textContent=rank;$('menuLevel').textContent='LEVEL '+s.level}
syncMenuProfile();syncControlModeUI();
gameUI.forEach(el=>el.classList.add('hidden'));
(()=>{const css=document.createElement('link');css.rel='stylesheet';css.href='economy.css';document.head.appendChild(css);const script=document.createElement('script');script.src='economy.js';document.body.appendChild(script);const feature=document.createElement('script');feature.src='features.js';document.body.appendChild(feature);const rankedCss=document.createElement('link');rankedCss.rel='stylesheet';rankedCss.href='ranked.css';document.head.appendChild(rankedCss);const rankedScript=document.createElement('script');rankedScript.src='ranked.js';document.body.appendChild(rankedScript);const clubsCss=document.createElement('link');clubsCss.rel='stylesheet';clubsCss.href='clubs.css';document.head.appendChild(clubsCss);const clubsScript=document.createElement('script');clubsScript.src='clubs.js';document.body.appendChild(clubsScript);const wcCss=document.createElement('link');wcCss.rel='stylesheet';wcCss.href='world-championship.css';document.head.appendChild(wcCss);const wcScript=document.createElement('script');wcScript.src='world-championship.js';document.body.appendChild(wcScript)})();
