(()=>{
  const stats={pass:0,set:0,spike:0,block:0,dive:0,serve:0,touches:0,started:Date.now()};
  let lastHome='0',lastAway='0';
  const load=()=>{try{const s=JSON.parse(localStorage.getItem('vvPerformance')||'null');if(s)Object.assign(stats,s)}catch(e){}};
  const save=()=>{try{localStorage.setItem('vvPerformance',JSON.stringify(stats))}catch(e){}};
  const grade=()=>{const total=stats.pass+stats.set+stats.spike+stats.block+stats.dive+stats.serve;if(!total)return '—';const score=Math.min(100,40+stats.serve*4+stats.pass*3+stats.set*4+stats.spike*6+stats.block*5+stats.dive*2);return score>=90?'S':score>=80?'A':score>=70?'B':score>=60?'C':'D'};
  const build=()=>{if(document.getElementById('performanceBtn'))return;const hud=document.getElementById('hud');if(!hud)return;const pause=document.getElementById('pauseBtn');const btn=document.createElement('button');btn.id='performanceBtn';btn.className='glass';btn.textContent='▦';btn.title='Performance Center';hud.appendChild(btn);const panel=document.createElement('div');panel.id='performancePanel';panel.className='performance-panel hidden';panel.innerHTML='<div class="performance-head"><b>MATCH PERFORMANCE</b><button id="performanceClose">×</button></div><div class="performance-grid"><div class="performance-stat"><strong id="psServe">0</strong><span>SERVES</span></div><div class="performance-stat"><strong id="psPass">0</strong><span>PASSES</span></div><div class="performance-stat"><strong id="psSet">0</strong><span>SETS</span></div><div class="performance-stat"><strong id="psSpike">0</strong><span>SPIKES</span></div><div class="performance-stat"><strong id="psBlock">0</strong><span>BLOCKS</span></div><div class="performance-stat"><strong id="psDive">0</strong><span>DIGS</span></div></div><div class="performance-footer"><span>SESSION GRADE <b class="performance-grade" id="psGrade">—</b></span><span id="psTime">0:00</span></div>';document.body.appendChild(panel);btn.onclick=()=>{panel.classList.toggle('hidden');render()};document.getElementById('performanceClose').onclick=()=>panel.classList.add('hidden');document.querySelectorAll('#controls .action').forEach(b=>b.addEventListener('click',()=>{const id=b.id.replace('Btn','');if(stats[id]!==undefined){stats[id]++;stats.touches++;save();render()}}));};
  const render=()=>{const map={psServe:'serve',psPass:'pass',psSet:'set',psSpike:'spike',psBlock:'block',psDive:'dive'};Object.keys(map).forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=stats[map[id]]});const g=document.getElementById('psGrade');if(g)g.textContent=grade();const t=document.getElementById('psTime');if(t){const sec=Math.floor((Date.now()-stats.started)/1000);t.textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0')}};
  const watchScore=()=>{const h=document.getElementById('homeScore'),a=document.getElementById('awayScore');if(!h||!a)return;const check=()=>{if(h.textContent!==lastHome||a.textContent!==lastAway){lastHome=h.textContent;lastAway=a.textContent;save();render()}};new MutationObserver(check).observe(h,{childList:true,characterData:true,subtree:true});new MutationObserver(check).observe(a,{childList:true,characterData:true,subtree:true})};
  load();const boot=()=>{build();watchScore();render()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(render,1000);
})();