(()=>{
const KEY='volleyverseRanked';
const tiers=[['BRONZE',0],['SILVER',100],['GOLD',250],['PLATINUM',450],['DIAMOND',700],['MASTER',1000],['GRANDMASTER',1350],['CHAMPION',1750]];
const defaults={rating:0,wins:0,losses:0,streak:0,season:1,placements:0,history:[]};
const load=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const tierFor=r=>{let out=tiers[0];tiers.forEach(t=>{if(r>=t[1])out=t});return out};
const record=won=>{const s=load();const delta=won?(24+Math.min(s.streak,4)*3):-(16+Math.min(s.streak,0)*0);s.rating=Math.max(0,s.rating+delta);if(won){s.wins++;s.streak=Math.max(0,s.streak+1)}else{s.losses++;s.streak=Math.min(0,s.streak-1)}s.placements=Math.min(10,s.placements+1);s.history.unshift({won,delta,date:Date.now()});s.history=s.history.slice(0,20);save(s);render();return {...s,delta,tier:tierFor(s.rating)}};
const render=()=>{const s=load(),tier=tierFor(s.rating);const r=document.getElementById('rankRating'),t=document.getElementById('rankTier'),w=document.getElementById('rankWins'),l=document.getElementById('rankLosses'),st=document.getElementById('rankStreak'),bar=document.getElementById('rankProgress');if(!r)return;r.textContent=s.rating+' RP';t.textContent=tier[0];w.textContent=s.wins;l.textContent=s.losses;st.textContent=Math.abs(s.streak);const next=tiers.find(x=>x[1]>s.rating);if(bar)bar.style.width=(next?Math.min(100,(s.rating-tier[1])/(next[1]-tier[1])*100:100)+'%';document.getElementById('rankSeason')?.textContent='SEASON '+String(s.season).padStart(2,'0');document.getElementById('rankPlacement')?.textContent=s.placements<10?'PLACEMENT '+s.placements+'/10':'RANKED READY'};
const open=()=>{let m=document.getElementById('rankedModal');if(!m){m=document.createElement('div');m.id='rankedModal';m.className='modal';m.innerHTML='<div class="modal-panel ranked-panel"><button class="modal-close" id="rankClose">×</button><span class="eyebrow" id="rankSeason">SEASON 01</span><h2 id="rankTier">BRONZE</h2><div class="rank-rating" id="rankRating">0 RP</div><div class="rank-track"><div id="rankProgress"></div></div><div class="rank-stats"><div><b id="rankWins">0</b><span>WINS</span></div><div><b id="rankLosses">0</b><span>LOSSES</span></div><div><b id="rankStreak">0</b><span>STREAK</span></div></div><p id="rankPlacement">PLACEMENT 0/10</p><div class="rank-actions"><button class="primary" id="rankWin">SIMULATE WIN + RP</button><button class="glass" id="rankLoss">SIMULATE LOSS</button></div><p class="rank-note">Ranked prototype: local rating, tiers, placement tracking and season-ready history. Online matchmaking and server-authoritative ratings come later.</p></div>';document.body.appendChild(m);document.getElementById('rankClose').onclick=()=>m.classList.add('hidden');document.getElementById('rankWin').onclick=()=>record(true);document.getElementById('rankLoss').onclick=()=>record(false)}render();m.classList.remove('hidden')};
window.VVRanked={load,save,record,open,tierFor,tiers};
})();