(()=>{
const KEY='volleyverseSeason';
const rewards=['100 COINS','TRAINING XP','150 COINS','5 GEMS','200 COINS','RANDOM COSMETIC','250 COINS','10 GEMS','300 COINS','ELITE BADGE','350 COINS','10 GEMS','400 COINS','RARE COSMETIC','450 COINS','15 GEMS','500 COINS','EPIC COSMETIC','750 COINS','CHAMPION FRAME'];
const load=()=>{try{return {level:1,xp:0,claimed:[],premium:false,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {level:1,xp:0,claimed:[],premium:false}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const need=l=>100+(l-1)*25;
const addXP=n=>{const s=load();s.xp+=n;while(s.xp>=need(s.level)&&s.level<20){s.xp-=need(s.level);s.level++}save(s);render();return s};
const claim=i=>{const s=load();if(i+1>s.level||s.claimed.includes(i))return;if(i>=19&&s.level<20)return;s.claimed.push(i);save(s);const r=rewards[i];const coins=Number((r.match(/^(\d+)/)||[])[1]||0);if(coins&&window.VVEconomy?.addCoins)window.VVEconomy.addCoins(coins);render()};
const render=()=>{const s=load(),fill=document.getElementById('seasonFill'),xp=document.getElementById('seasonXP'),level=document.getElementById('seasonLevel'),list=document.getElementById('seasonLevels');if(!list)return;const required=need(s.level);if(fill)fill.style.width=Math.min(100,s.level===20?100:s.xp/required*100)+'%';if(xp)xp.textContent=s.level===20?'MAX LEVEL':s.xp+' / '+required+' XP';if(level)level.textContent='LEVEL '+s.level;list.innerHTML=rewards.map((r,i)=>{const unlocked=i<s.level,claimed=s.claimed.includes(i);return `<button class="season-level ${i+1===s.level?'current':''} ${claimed?'claimed':''}" data-season="${i}" ${!unlocked?'disabled':''}><b>LV ${i+1}</b><span>FREE REWARD</span><strong>${r}</strong>${claimed?'<small>✓ CLAIMED</small>':unlocked?'<small>CLAIM</small>':'<small>LOCKED</small>'}</button>`}).join('')};
const open=()=>{let m=document.getElementById('seasonModal');if(!m){m=document.createElement('div');m.id='seasonModal';m.className='modal';m.innerHTML='<div class="modal-panel season-panel"><button class="modal-close" id="seasonClose">×</button><div class="season-head"><div><span class="eyebrow">SEASON 01</span><h2>RISE OF THE CHAMPIONS</h2><p>Earn Season XP and unlock milestone rewards.</p></div><b id="seasonLevel">LEVEL 1</b></div><div class="season-track"><div class="season-fill" id="seasonFill"></div></div><div class="season-xp"><span id="seasonXP">0 / 100 XP</span><span>20 LEVELS</span></div><div id="seasonLevels" class="season-levels"></div><button class="primary" id="seasonTrain">EARN +50 SEASON XP</button><p class="season-note">Season rewards are prototype progression. Premium pass and online season synchronization will be added later.</p></div>';document.body.appendChild(m);document.getElementById('seasonClose').onclick=()=>m.classList.add('hidden');document.getElementById('seasonTrain').onclick=()=>addXP(50);document.getElementById('seasonLevels').addEventListener('click',e=>{const b=e.target.closest('[data-season]');if(b)claim(Number(b.dataset.season))})}render();m.classList.remove('hidden')};
window.VVSeason={load,save,addXP,open};
})();