const http=require('http');const crypto=require('crypto');
const sessions=new Map(),queues=new Map(),connections=new Map();
const uid=p=>p+'_'+crypto.randomBytes(6).toString('hex');
function makeSession(region='SEA',mode='RANKED'){const s={schema:'VV_SERVER_SESSION',version:1,id:uid('match'),region,mode,tick:0,status:'WAITING',createdAt:Date.now(),players:new Map(),scores:{home:0,away:0},sets:{home:0,away:0},ball:{x:0,y:1,z:0,vx:0,vy:0,vz:0},lastActivity:Date.now()};sessions.set(s.id,s);return s}
function pub(s){return {...s,players:[...s.players.values()]}}
function broadcast(s,msg){for(const p of s.players.values()){const c=connections.get(p.id);if(c?.readyState===1)c.send(JSON.stringify(msg))}}
function assign(session,p){const team=session.players.size===0?'home':'away';session.players.set(p.id,{id:p.id,team,connected:true,lastSeen:Date.now(),input:{x:0,z:0,action:null}});connections.set(p.id,p.ws)}
function enqueue(p){const q=queues.get(p.mode)||[];q.push(p);queues.set(p.mode,q);if(q.length>=2){const a=q.shift(),b=q.shift(),s=makeSession(a.region,p.mode);assign(s,a);assign(s,b);s.status='LIVE';broadcast(s,{type:'SESSION_READY',session:pub(s)});return s}return null}
function send(ws,o){if(ws.readyState===1)ws.send(JSON.stringify(o))}
function parse(req){return new Promise(resolve=>{let b='';req.on('data',d=>b+=d);req.on('end',()=>{try{resolve(JSON.parse(b||'{}'))}catch{resolve(null)}})})}
function handleMessage(ws,msg){if(!msg||typeof msg.type!=='string')return;const pid=ws.playerId;if(msg.type==='QUEUE'){const mode=String(msg.mode||'RANKED').toUpperCase(),region=String(msg.region||'SEA').toUpperCase();ws.playerId=pid||uid('player');ws.mode=mode;ws.region=region;const s=enqueue({id:ws.playerId,mode,region,ws});send(ws,{type:'QUEUED',playerId:ws.playerId,mode,region});if(s) broadcast(s,{type:'SESSION_READY',session:pub(s)});return}if(msg.type==='INPUT'){const s=sessions.get(ws.sessionId);const p=s?.players.get(pid);if(!p)return;p.input={x:Math.max(-1,Math.min(1,Number(msg.x)||0)),z:Math.max(-1,Math.min(1,Number(msg.z)||0)),action:typeof msg.action==='string'?msg.action:null};p.lastSeen=Date.now();return}if(msg.type==='PING'){send(ws,{type:'PONG',clientTime:msg.clientTime||Date.now(),serverTime:Date.now()});return}if(msg.type==='RECONNECT'){const s=sessions.get(String(msg.sessionId||''));const p=s?.players.get(pid);if(s&&p){ws.sessionId=s.id;connections.set(pid,ws);p.connected=true;p.lastSeen=Date.now();send(ws,{type:'RECONNECTED',session:pub(s)});return}send(ws,{type:'RECONNECT_FAILED'})}}
function attach(ws){ws.on('message',raw=>{try{handleMessage(ws,JSON.parse(raw.toString()))}catch{send(ws,{type:'ERROR',code:'BAD_MESSAGE'})}});ws.on('close',()=>{const pid=ws.playerId;if(!pid)return;connections.delete(pid);for(const s of sessions.values()){const p=s.players.get(pid);if(p){p.connected=false;p.lastSeen=Date.now();broadcast(s,{type:'PLAYER_DISCONNECTED',playerId:pid,graceSeconds:15});}}});ws.on('error',()=>{})}
function simulationTick(){for(const s of sessions.values()){if(s.status!=='LIVE')continue;s.tick++;s.lastActivity=Date.now();for(const p of s.players.values()){if(!p.connected&&Date.now()-p.lastSeen>15000){p.aiTakeover=true} }broadcast(s,{type:'SNAPSHOT',snapshot:{schema:'VV_MATCH_SNAPSHOT',version:1,tick:s.tick,timestamp:Date.now(),sessionId:s.id,state:{scores:s.scores,sets:s.sets,ball:s.ball,players:[...s.players.values()].map(p=>({id:p.id,team:p.team,connected:p.connected,aiTakeover:!!p.aiTakeover,input:p.input}))}}})}}
setInterval(simulationTick,50);
const httpServer=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');if(req.url==='/health'){res.end(JSON.stringify({ok:true,service:'volleyverse-server',sessions:sessions.size,connections:connections.size,queues:[...queues.values()].reduce((n,q)=>n+q.length,0)}));return}if(req.url==='/session'&&req.method==='POST'){const p=await parse(req);if(!p){res.statusCode=400;return res.end(JSON.stringify({error:'invalid_request'}));}const playerId=p.playerId||uid('player'),mode=String(p.mode||'RANKED').toUpperCase(),region=String(p.region||'SEA').toUpperCase();const s=enqueue({id:playerId,mode,region,ws:null});res.end(JSON.stringify(s?{queued:false,session:pub(s),playerId}:{queued:true,playerId,mode,region}));return}res.statusCode=404;res.end(JSON.stringify({error:'not_found'}))});
// Optional WebSocket dependency is intentionally isolated here for deployment.
let WebSocketServer;try{({WebSocketServer}=require('ws'))}catch{WebSocketServer=null}
if(WebSocketServer){const wss=new WebSocketServer({server:httpServer,path:'/ws'});wss.on('connection',attach)}else console.warn('Install ws for realtime WebSocket transport: npm install ws');
const port=Number(process.env.PORT||3001);httpServer.listen(port,()=>console.log('VOLLEYVERSE REALTIME SERVER '+port));
module.exports={sessions,queues,connections,makeSession,enqueue,pub};