const http=require('http'),crypto=require('crypto');const sessions=new Map(),queues=new Map(),connections=new Map();const uid=p=>p+'_'+crypto.randomBytes(6).toString('hex');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function makeSession(region='SEA',mode='RANKED'){const s={schema:'VV_SERVER_SESSION',version:2,id:uid('match'),region,mode,tick:0,status:'WAITING',createdAt:Date.now(),players:new Map(),scores:{home:0,away:0},sets:{home:0,away:0},setNumber:1,serving:'home',rally:{active:false,serveTeam:'home',touches:0,lastTouch:null},ball:{x:0,y:1.05,z:0,vx:0,vy:0,vz:0,heldBy:null},lastActivity:Date.now(),matchWinner:null};sessions.set(s.id,s);return s}
function pub(s){return {...s,players:[...s.players.values()]}}
function send(ws,o){if(ws?.readyState===1)ws.send(JSON.stringify(o))}function broadcast(s,o){for(const p of s.players.values())send(connections.get(p.id),o)}
function assign(s,p){const team=s.players.size===0?'home':'away';s.players.set(p.id,{id:p.id,team,connected:true,aiTakeover:false,lastSeen:Date.now(),x:team==='home'?-2:2,z:team==='home'?-2:2,y:0,input:{x:0,z:0,action:null}});connections.set(p.id,p.ws)}
function enqueue(p){const q=queues.get(p.mode)||[];q.push(p);queues.set(p.mode,q);if(q.length<2)return null;const a=q.shift(),b=q.shift(),s=makeSession(a.region,p.mode);assign(s,a);assign(s,b);s.status='LIVE';return s}
function point(s,winner){s.scores[winner]++;s.rally={active:false,serveTeam:winner,touches:0,lastTouch:null};s.serving=winner;s.ball={x:0,y:1.05,z:0,vx:0,vy:0,vz:0,heldBy:null};for(const p of s.players.values()){p.x=p.team==='home'?-2:2;p.z=p.team==='home'?-2:2;p.input.action=null}const target=s.setNumber===5?15:25;const lead=s.scores[winner]-s.scores[winner==='home'?'away':'home'];if(s.scores[winner]>=target&&lead>=2){s.sets[winner]++;s.scores={home:0,away:0};if(s.sets[winner]>=3){s.status='FINISHED';s.matchWinner=winner}else{s.setNumber++;s.serving=winner}}broadcast(s,{type:'POINT',winner,session:pub(s)})}
function act(s,p,a){if(!a)return;if(a==='serve'&&!s.rally.active&&s.serving===p.team){s.rally.active=true;s.rally.serveTeam=p.team;s.rally.touches=1;s.rally.lastTouch=p.id;s.ball.vx=(p.input.x||0)*5;s.ball.vz=p.team==='home'?5:-5;s.ball.vy=5;s.ball.heldBy=null;return}if(!s.rally.active)return;if(['pass','set','spike','block','dig'].includes(a)){s.rally.touches++;s.rally.lastTouch=p.id;const dir=p.team==='home'?1:-1;if(a==='pass'){s.ball.vy=4;s.ball.vz=dir*3}else if(a==='set'){s.ball.vy=6;s.ball.vz=dir*1.5}else if(a==='spike'){s.ball.vy=2;s.ball.vz=dir*10}else if(a==='dig'){s.ball.vy=5;s.ball.vz=dir*3}else if(a==='block'){s.ball.vy=4;s.ball.vz=-dir*7}}}
function simulate(s){if(s.status!=='LIVE')return;s.tick++;const dt=.05;for(const p of s.players.values()){if(!p.connected&&Date.now()-p.lastSeen>15000)p.aiTakeover=true;const ix=p.aiTakeover?(p.team==='home'?0.15:-0.15):p.input.x,iz=p.aiTakeover?0:p.input.z;p.x=clamp(p.x+ix*4.2*dt,p.team==='home'?-4.3:-.1,p.team==='home'?.1:4.3);p.z=clamp(p.z+iz*4.2*dt,-4.4,4.4);if(p.input.action){act(s,p,p.input.action);p.input.action=null}}if(s.rally.active){s.ball.vy-=9.8*dt;s.ball.x+=s.ball.vx*dt;s.ball.y+=s.ball.vy*dt;s.ball.z+=s.ball.vz*dt;if(s.ball.z>5||s.ball.z<-5||s.ball.y<0.15){point(s,s.ball.z>0?'home':'away')}}s.lastActivity=Date.now();broadcast(s,{type:'SNAPSHOT',snapshot:{schema:'VV_MATCH_SNAPSHOT',version:2,tick:s.tick,timestamp:Date.now(),sessionId:s.id,state:{status:s.status,scores:s.scores,sets:s.sets,setNumber:s.setNumber,serving:s.serving,rally:s.rally,ball:s.ball,players:[...s.players.values()].map(p=>({id:p.id,team:p.team,connected:p.connected,aiTakeover:p.aiTakeover,x:p.x,y:p.y,z:p.z}))}}})}
function handle(ws,m){if(!m||typeof m.type!=='string')return;const pid=ws.playerId||uid('player');ws.playerId=pid;if(m.type==='QUEUE'){ws.mode=String(m.mode||'RANKED').toUpperCase();ws.region=String(m.region||'SEA').toUpperCase();const s=enqueue({id:pid,mode:ws.mode,region:ws.region,ws});send(ws,{type:'QUEUED',playerId:pid,mode:ws.mode,region:ws.region});if(s){for(const p of s.players.values()){p.ws=null;const c=connections.get(p.id);if(c){c.sessionId=s.id;send(c,{type:'SESSION_READY',session:pub(s)})}}}return}if(m.type==='INPUT'){const s=sessions.get(ws.sessionId),p=s?.players.get(pid);if(!p)return;p.input={x:clamp(Number(m.x)||0,-1,1),z:clamp(Number(m.z)||0,-1,1),action:typeof m.action==='string'?m.action:null};p.lastSeen=Date.now();return}if(m.type==='PING'){send(ws,{type:'PONG',clientTime:m.clientTime||Date.now(),serverTime:Date.now()});return}if(m.type==='RECONNECT'){const s=sessions.get(String(m.sessionId||'')),p=s?.players.get(pid);if(s&&p){ws.sessionId=s.id;p.connected=true;p.aiTakeover=false;p.lastSeen=Date.now();connections.set(pid,ws);send(ws,{type:'RECONNECTED',session:pub(s)})}else send(ws,{type:'RECONNECT_FAILED'})}}
function attach(ws){ws.on('message',r=>{try{handle(ws,JSON.parse(r.toString()))}catch{send(ws,{type:'ERROR',code:'BAD_MESSAGE'})}});ws.on('close',()=>{if(!ws.playerId)return;connections.delete(ws.playerId);for(const s of sessions.values()){const p=s.players.get(ws.playerId);if(p){p.connected=false;p.lastSeen=Date.now();broadcast(s,{type:'PLAYER_DISCONNECTED',playerId:ws.playerId,graceSeconds:15})}}})}
setInterval(()=>{for(const s of sessions.values())simulate(s)},50);const httpServer=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.url==='/health')return res.end(JSON.stringify({ok:true,service:'volleyverse-authoritative-server',sessions:sessions.size,connections:connections.size}));res.statusCode=404;res.end(JSON.stringify({error:'not_found'}))});const {WebSocketServer}=require('ws');new WebSocketServer({server:httpServer,path:'/ws'}).on('connection',attach);httpServer.listen(Number(process.env.PORT||3001),()=>console.log('VOLLEYVERSE AUTHORITATIVE SERVER READY'));module.exports={sessions,queues,connections,makeSession,enqueue,simulate,point};